@Library("Shared") _
pipeline{
    
    agent { label "dev"};
    
    stages{
        stage("Code Clone"){
            steps{
               script{
                   clone("https://github.com/Mohit108arora/Devops-Project.git")
               }
            }
        }
        stage("Trivy File System Scan"){
            steps{
                script{
                    trivy_fs()
                }
            }
        }
        stage("Build"){
            steps{
                sh "docker build -t myflask-app ."
            }
            
        }
        stage("Test"){
            steps{
                echo "Developer / Tester tests likh ke dega..."
            }
            
        }
        stage("Push to Docker Hub"){
            steps{
                script{
                    docker_push("dockerHubCreds","myflask-app")
                }  
            }
        }
        stage("Deploy"){
            steps{
                sh "docker compose up -d --build myflask-app"
            }
        }
    }

post{
        success{
            script{
                emailext from: 'mohit.arora1605@gmail.com',
                to: 'mohit.arora1605@gmail.com',
                body: 'Build success for Demo CICD App',
                subject: 'Build success for Demo CICD App'
            }
        }
        failure{
            script{
                emailext from: 'mohit.arora1605@gmail.com.com',
                to: 'mohit.arora1605@gmail.com.com',
                body: 'Build Failed for Demo CICD App',
                subject: 'Build Failed for Demo CICD App'
            }
        }
    }
}
